### ISSUE TITLE
Tests fail on MacOS

### ISSUE THREAD

**Issue by GlenKelley** [go-gl/examples#28]
Firstly, thanks for the work in writing OpenGL bindings for go.

I'm developing on a mac (10.8.6 - Lion), and have been using the go-gl package with success.

However, I have noticed sporadic crashes and other unexplained behaviour even simple test programs supplied in this examples repository.

At the moment running `go test` from `examples/gl` produces the segfault below

I'm happy to investigate the cause/fix myself, I just wanted to check that these test suites are still relevant and if there are any common 'gotchas' that I should be aware of in regards to my GL/GLUT/GLFW/GLEW installation.

    SIGSEGV: segmentation violation
    PC=0x0
    signal arrived during cgo execution

    github.com/go-gl/gl._Cfunc_glTexImage3D(0x806f, 0x200001908, 0x200000002, 0x190800000000, 0xc200001404, ...)
    	github.com/go-gl/gl/_obj/_cgo_defun.c:3484 +0x2f
    github.com/go-gl/gl.TexImage3D(0x806f, 0x0, 0x1908, 0x2, 0x2, ...)
    	github.com/go-gl/gl/_obj/attriblocation.cgo1.go:4416 +0x9f
    github.com/go-gl/examples/gl.func·005()
    	/Users/glen/Development/golib/src/github.com/go-gl/examples/gl/gl_test.go:87 +0x94
    github.com/go-gl/testutils.func·001()
    	/Users/glen/Development/golib/src/github.com/go-gl/testutils/gltest.go:53 +0x254
    created by github.com/go-gl/testutils.StartOpenGL
    	/Users/glen/Development/golib/src/github.com/go-gl/testutils/gltest.go:58 +0x1f

    goroutine 1 [chan receive]:
    testing.RunTests(0x168388, 0x22c8e0, 0x14, 0x14, 0x1, ...)
    	/usr/local/go/src/pkg/testing/testing.go:434 +0x88e
    testing.Main(0x168388, 0x22c8e0, 0x14, 0x14, 0x22f360, ...)
    	/usr/local/go/src/pkg/testing/testing.go:365 +0x8a
    main.main()
    	github.com/go-gl/examples/gl/_test/_testmain.go:81 +0x9a

    goroutine 2 [syscall]:

    goroutine 7 [chan send]:
    github.com/go-gl/testutils.OnTheMainThread(0xc200069360, 0x1682b8)
    	/Users/glen/Development/golib/src/github.com/go-gl/testutils/gltest.go:27 +0x7a
    github.com/go-gl/examples/gl.TestTexImage3D(0xc20009f120)
    	/Users/glen/Development/golib/src/github.com/go-gl/examples/gl/gl_test.go:105 +0x6c
    testing.tRunner(0xc20009f120, 0x22c910)
    	/usr/local/go/src/pkg/testing/testing.go:353 +0x8a
    created by testing.RunTests
    	/usr/local/go/src/pkg/testing/testing.go:433 +0x86b
    rax     0x806f
    rbx     0x1404
    rcx     0x2
    rdx     0x1908
    rdi     0x806f
    rsi     0x0
    rbp     0xb0103e40
    rsp     0xb0103e08
    r8      0x2
    r9      0x2
    r10     0x2cc098
    r11     0x1908
    r12     0x0
    r13     0x502b98270d8
    r14     0x1326f7d7164fe600
    r15     0xbb14a
    rip     0x0
    rflags  0x10202
    cs      0x2b
    fs      0x0
    gs      0x0
    exit status 2
    FAIL	github.com/go-gl/examples/gl	0.894s

**Comment by SamMorrowDrums** [comment]
Hi, I'm on OSX Yosemite with homebrew install of `glfw2`, `glfw3`, `glew`, 'sdl' & `SDL_image`, which were all the dependencies. Some tests are also failing for me. Below is the output:

```
go test
2015/01/31 13:14:45 === gltext/truetype
================================================================================
github.com/go-gl/examples/gltext/truetype
--------------------------------------------------------------------------------
2015/01/31 13:14:46 === mathgl/opengl-tutorial/objloader
================================================================================
github.com/go-gl/mathgl (download)
github.com/go-gl/mathgl/mgl32
github.com/go-gl/examples/mathgl/opengl-tutorial/objloader
--------------------------------------------------------------------------------
2015/01/31 13:14:51 === glfw3/modern
================================================================================
github.com/go-gl/examples/glfw3/modern
--------------------------------------------------------------------------------


2015/01/31 13:14:52 === nehe/06
================================================================================
github.com/go-gl/examples/nehe/06
--------------------------------------------------------------------------------
2015/01/31 13:14:54 === nehe/08
================================================================================
github.com/go-gl/examples/nehe/08
--------------------------------------------------------------------------------
2015/01/31 13:14:56 === nehe/03
================================================================================
github.com/go-gl/examples/nehe/03
--------------------------------------------------------------------------------
2015/01/31 13:15:02 === gl
================================================================================
-- subtest:  gl
=== RUN TestTexImage1D
--- PASS: TestTexImage1D (0.63s)
=== RUN TestTexImage2D
--- PASS: TestTexImage2D (0.01s)
=== RUN TestTexImage3D
--- PASS: TestTexImage3D (0.02s)
=== RUN TestTexSubImage1D
--- PASS: TestTexSubImage1D (0.01s)
=== RUN TestTexSubImage2D
--- PASS: TestTexSubImage2D (0.02s)
=== RUN TestTexSubImage3D
--- PASS: TestTexSubImage3D (0.01s)
=== RUN TestBufferData
--- PASS: TestBufferData (0.03s)
=== RUN TestBufferSubData
--- PASS: TestBufferSubData (0.01s)
=== RUN TestGetBufferSubData
--- PASS: TestGetBufferSubData (0.02s)
=== RUN TestAttribPointer
panic: vertex shader error: ERROR: 0:2: 'foo' : syntax error: Array size must appear after variable name


goroutine 6 [running, locked to thread]:
github.com/go-gl/examples/gl.newProgram(0xc2080345c0)
	/Users/Sam/src/github.com/go-gl/examples/gl/gl_test.go:273 +0x1be
github.com/go-gl/examples/gl.func·019()
	/Users/Sam/src/github.com/go-gl/examples/gl/gl_test.go:300 +0x30
github.com/go-gl/testutils.func·001()
	/Users/Sam/src/github.com/go-gl/testutils/gltest.go:53 +0x477
created by github.com/go-gl/testutils.StartOpenGL
	/Users/Sam/src/github.com/go-gl/testutils/gltest.go:58 +0x25

goroutine 1 [chan receive, locked to thread]:
testing.RunTests(0x41c1cd8, 0x424b6a0, 0x14, 0x14, 0x4260501)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc2080400f0, 0x424c3c0)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/go-gl/examples/gl/_test/_testmain.go:90 +0x1d5

goroutine 15 [chan send]:
github.com/go-gl/testutils.OnTheMainThread(0xc20802a8a0, 0x41c1c48)
	/Users/Sam/src/github.com/go-gl/testutils/gltest.go:27 +0x96
github.com/go-gl/examples/gl.TestAttribPointer(0xc20805e510)
	/Users/Sam/src/github.com/go-gl/examples/gl/gl_test.go:315 +0x99
testing.tRunner(0xc20805e510, 0x424b778)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:555 +0xa8b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
FAIL	github.com/go-gl/examples/gl	0.800s
--- FAIL: TestExamples (18.64s)
	examples_test.go:95: Process mathgl/opengl-tutorial/objloader died unexpectedly after 1.189658ms: "fork/exec bin/mathgl/opengl-tutorial/objloader: permission denied"
	examples_test.go:39: Failed to run 'go test':  exit status 1
FAIL
exit status 1
FAIL	github.com/go-gl/examples	18.695s
```

**Comment by andcode365** [comment]
Hi. I encountered the same problem as @3zcurdia's (see https://github.com/go-gl/examples/issues/28#issuecomment-48787759) on OSX 10.10.2.

I moved some lines in examples/glfw3/triangle/triangle.go to avoid the problem like this.
```c++
// create & bind vertex array here
// OpenGL requires us to have a vertex array object bound
vertexArray := gl.GenVertexArray()
vertexArray.Bind()

vShader := glh.Shader{gl.VERTEX_SHADER, loadDataFile("triangle.v.glsl")}
fShader := glh.Shader{gl.FRAGMENT_SHADER, loadDataFile("triangle.f.glsl")}
program := glh.NewProgram(vShader, fShader)
program.Use()
```

I think glh.NewProgram() has 2 issues.

0. It doesn't print program.GetInfoLog() message when gl.VALIDATE_STATUS is false.
0. Is it appropriate to validate gl.Program here?

thanks.

**Comment by shurcooL** [comment]
I don't think this repository is well maintained. It has mostly one-off contributions, but no active updating from authors to keep it up with the latest changes.

Personally, I don't use `glh` in any of my projects, so I can't know if it's no longer working.
