### ISSUE TITLE
Proposal: Reboot go-gl/examples, be more selective.

### ISSUE THREAD

**Issue by shurcooL** [go-gl/examples#38]
@go-gl Please see the proposal at https://groups.google.com/forum/#!topic/go-gl/PXxMYXEhYEY and leave your feedback.

I hope we can move fast on this, because people deciding to try Go and OpenGL after reading https://sourcegraph.com/blog/live/gopherconindia/112025389257 will not have a good experience.

**Comment by shurcooL** [comment]
We've decided to go ahead with it (with LGTM from @shurcooL, @slimsag and @Jragonmiris).

**Comment by pwaller** [comment]
:+1:
